name: Losic Lab Research
description: Science updates on immunogenomics from the Losic lab at the Icahn School of Medicine at Mount Sinai
url: https://losiclab.github.io

markdown: redcarpet
permalink: /:categories/:title/
future: true

redcarpet:
  extensions:
   - tables
   - no_intra_emphasis
   - autolink
   - superscript
   - strikethrough

exclude:
  - "*.class"
  - "*.cpp"
  - "*.h"
  - "*.hh"
  - "*.ipynb"
  - "*.jar"
  - "*.java"
  - "*.nb"
  - "*.py"
  - "*.R"
  - "*.rb"
  - "*.Rmd"
  - "*.branches"
  - "*.csv"
  - "*.fasta"
  - "*.kml"
  - "*.log"
  - "*.mcc"
  - "*.newick"
  - "*.nex"
  - "*.tsv"
  - "*.tips"
  - "*.trees"
  - "*.txt"
  - "*.zip"
  - "*.gz"
  - "*.tiff"
  - "*.xml"
  - "Gemfile"
  - "Gemfile.lock"
  - "Icon"

projects:
  - LosicLab/starchip
  
